
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Drug related crime trends in SF
description: >- # this means to ignore newlines until "baseurl:"
  An analysis of the trends in drug/narcotics related crime in the San Francisco area in the time period 2003-2024.
github:
  is_project_page: true
show_downloads: true


# Build settings
remote_theme: pages-themes/cayman@v0.2.0
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

